export const ApiContextType = {
  UPDATE_PEOPLE: "UPDATE_PEOPLE",
  UPDATE_DIR_PATH: "UPDATE_DIR_PATH",
  START_FETCH_SPEND_LOADING: "START_FETCH_SPEND_LOADING",
  STOP_FETCH_SPEND_LOADING: "STOP_FETCH_SPEND_LOADING",
  START_FETCH_PEOPLE_LOADING: "START_FETCH_PEOPLE_LOADING",
  STOP_FETCH_PEOPLE_LOADING: "STOP_FETCH_PEOPLE_LOADING",
  CLOSE_DIALOG: "CLOSE_DIALOG",
  OPEN_DIALOG: "OPEN_DIALOG",
};
